import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import React from "react";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`grid min-h-screen w-full ${user && "md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]"}`}
        >
          {user ? <Sidebar /> : null}
          <div className="flex flex-col">
            <Header user={user} />
            <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6 justify-center">
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
